using Microsoft.AspNetCore.Authorization;

namespace Application.Security;

/// <summary>
/// Attribute used to enforce privilege-based authorization in an ASP.NET Core application.
/// </summary>
/// <remarks>
/// The <c>RequirePrivilegeAttribute</c> facilitates authorization by specifying a set of required
/// privileges to access a given class or method. It extends the <see cref="Microsoft.AspNetCore.Authorization.AuthorizeAttribute"/>
/// and dynamically applies a constructed policy based on the provided privileges.
/// </remarks>
/// <param name="privileges">
/// An array of strings representing the required privileges for access. The privilege names
/// are concatenated into a single policy string using a predefined prefix and delimiter.
/// </param>
/// <note type="implementation">
/// The policy is generated by combining a fixed prefix ("RequirePrivileges") with a semicolon-separated
/// list of privilege names.
/// </note>
/// <remarks>
/// This attribute is compatible with the ASP.NET Core dependency injection framework and can
/// be used with any authorization system that relies on policies.
/// </remarks>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Class, AllowMultiple = true)]
public class RequirePrivilegeAttribute : AuthorizeAttribute
{
    public const string Prefix = "RequirePrivileges";

    public RequirePrivilegeAttribute(params string[] privileges)
    {
        Policy = $"{Prefix}:{string.Join(";", privileges)}";
    }
}
